cloudboost/cloudboost/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cloudboost/', include('elasticsearch_and_redis_app.urls')),
    url(r'^admin/', admin.site.urls),
]

cloudboost/elasticsearch_and_redis_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
app_name = 'elasticsearch_and_redis_app'

urlpatterns = [
    # ex: /cloudboost/
    url(r'^$', views.cloudboost, name='cloudboost'),
    # ex: /cloudboost/index/    
    url(r'^index/$', views.index, name='index'),
    # ex: /cloudboost/search/
    url(r'^search/$', views.search, name='search'),    
]

cloudboost/elasticsearch_and_redis_app/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
@python_2_unicode_compatible


class Books(models.Model): #but no need further to make this model
    # book_id = models.IntegerField()
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.name

cloudboost/elasticsearch_and_redis_app/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import loader
from datetime import datetime
from cloudboost.settings import es,rds
from django.views.decorators.csrf import csrf_exempt
# import json



def cloudboost(request):
    template = loader.get_template('elasticsearch_and_redis_app/index.html')
    context = {}        
    
    return HttpResponse("Hello, world. This is home page"+template.render(context, request))

@csrf_exempt
def index(request):
    # book = get_object_or_404(Books)
    if request.method == 'GET':
    	key=request.GET['key']
    	result=rds.get(key) 
    	return HttpResponse(result)
    elif request.method == 'POST':
    	message = request.POST['message']
    	res1 = es.index(index="test-index", doc_type='cloudboost', body={"message": message, "timestamp": datetime.now()})
    	res2=rds.set("message",message)#since I had to index only one item, i.e. message, I only create a key message,
    								# otherwise I would have used list in Redis    	
    	# res1=json.dumps(res1, sort_keys=False, indent=4, separators=(',', ': '))
    	response="\n\n".join([str(res1),str(res2)])
    	
    	# template = loader.get_template('elasticsearch_and_redis_app/insert.html')
    	# context={}
    	return HttpResponse(response)
    	
    else:
    	return HttpResponse("GET/POST required")

def search(request):
	res = es.search(index="test-index", body={"query": {"match": {"message": request.GET['message']} }})
	ret = []
	for hit in res['hits']["hits"]:
		ret.append(hit['_source'])
	return HttpResponse(str(ret)) 

cloudboost/elasticsearch_and_redis_app/templates/elasticsearch_and_redis_app/index.html
<!-- <br>
<a href="/cloudboost/index/" target="_blank">Index</a>
<br>
<a href="/cloudboost/search/" target="_blank">Search</a> -->

cloudboost/elasticsearch_and_redis_app/templates/elasticsearch_and_redis_app/insert.html
<h1>Give me a message :)</h1>


<form action="{% url 'elasticsearch_and_redis_app:index' %}" method="post">
{% csrf_token %}
<label>Give me a message :</label><br>
<input type="text" name="message" value="default"><br>
<input type="submit" value="Submit" />
</form>

<form action="{% url 'elasticsearch_and_redis_app:index' %}" method="get">
{% csrf_token %}
<label>Search a value from Redis(Provide an index)</label><br>
<input type="text" name="index" value="1"><br>
<input type="submit" value="Submit" />
</form>